import { NextResponse } from "next/server";
import OpenAI from "openai";
import { z } from "zod";

const bodySchema = z.object({
  topic: z.string().min(3, "Topic is required"),
  audience: z.string().min(1).default("LinkedIn network"),
  tone: z.string().min(1).default("Thoughtful and professional"),
  keyPoints: z.array(z.string().min(1)).optional(),
  callToAction: z.string().optional(),
  hookStyle: z.string().optional(),
  hashtags: z.array(z.string().min(1)).optional(),
  brandVoice: z.string().optional(),
  length: z.enum(["short", "medium", "long"]).default("medium"),
});

export async function POST(request: Request) {
  const apiKey = process.env.OPENAI_API_KEY;

  if (!apiKey) {
    return NextResponse.json(
      { error: "OPENAI_API_KEY is not configured" },
      { status: 500 },
    );
  }

  let parsedBody;
  try {
    const body = await request.json();
    parsedBody = bodySchema.safeParse(body);
  } catch (error) {
    return NextResponse.json(
      { error: "Invalid JSON payload", details: String(error) },
      { status: 400 },
    );
  }

  if (!parsedBody.success) {
    return NextResponse.json(
      { error: "Validation failed", details: parsedBody.error.format() },
      { status: 422 },
    );
  }

  const {
    topic,
    audience,
    tone,
    keyPoints,
    callToAction,
    hookStyle,
    hashtags,
    brandVoice,
    length,
  } = parsedBody.data;

  const lengthGuidance =
    length === "short"
      ? "Keep it under 120 words."
      : length === "long"
      ? "You can go up to 260 words and use short paragraphs."
      : "Aim for about 180 words using concise paragraphs.";

  const openai = new OpenAI({ apiKey });

  try {
    const response = await openai.responses.create({
      model: "gpt-4o-mini",
      input: [
        {
          role: "system",
          content: [
            {
              type: "input_text",
              text: [
                "You are PostPilot, an AI communication strategist who writes scroll-stopping LinkedIn posts.",
                "Every draft must:",
                "- Lead with a strong hook tailored to the specified hook style.",
                "- Use friendly, human language with plenty of specificity.",
                "- Reference the provided key points naturally.",
                "- Address the stated audience directly.",
                "- Close with a relevant call-to-action if provided.",
                "- Finish with a compact list of 3-5 hashtags, each prefixed with '#'.",
              ].join(" "),
            },
          ],
        },
        {
          role: "user",
          content: [
            {
              type: "input_text",
              text: [
                `Topic: ${topic}`,
                brandVoice ? `Brand voice: ${brandVoice}` : null,
                `Primary audience: ${audience}`,
                `Tone: ${tone}`,
                hookStyle ? `Hook style: ${hookStyle}` : null,
                keyPoints?.length
                  ? `Key points to weave in: ${keyPoints.join("; ")}`
                  : null,
                callToAction
                  ? `Call to action to close with: ${callToAction}`
                  : null,
                hashtags?.length
                  ? `Must-use hashtags (mix with your own choices): ${hashtags.join(", ")}`
                  : null,
                lengthGuidance,
                "Return the response as markdown with short paragraphs and bullet points only if necessary.",
              ]
                .filter(Boolean)
                .join("\n"),
            },
          ],
        },
      ],
      max_output_tokens: 750,
    });

    const draft = response.output_text?.trim();

    if (!draft) {
      return NextResponse.json(
        { error: "No content generated by the model" },
        { status: 502 },
      );
    }

    return NextResponse.json({ draft });
  } catch (error) {
    console.error("Generation error", error);
    return NextResponse.json(
      {
        error: "Failed to generate post",
        details:
          error instanceof Error ? error.message : "Unknown error occurred",
      },
      { status: 500 },
    );
  }
}
